.PHONY: all
all: sfot
sfot: sfot.o sfotlib.o sfotcommon.o
		gcc -Wextra -Wconversion -pedantic -o sfot sfot.o sfotlib.o sfotcommon.o -O3 -std=gnu99;
		rm *.o;
sfot.o: sfot.c sfotlib.h
		gcc -Wextra -Wconversion -pedantic -c -g sfot.c -O3 -std=gnu99;
sfotlib.o: sfotlib.c sfotlib.h
		gcc -Wextra -Wconversion -pedantic -c -g sfotlib.c -O3 -std=gnu99;
sfotcommon.o: sfotcommon.c sfotcommon.h
		gcc -Wextra -Wconversion -pedantic -c -g sfotcommon.c -O3 -std=gnu99;
clean :
		rm *.o