.PHONY: all
all: sfot
sfot: main.o
		gcc -Wextra -Wconversion -pedantic -o sfot main.o -O3 -std=gnu99;
		rm *.o;
main.o: main.c main.h
		gcc -Wextra -Wconversion -pedantic -c -g main.c -O3 -std=gnu99;
clean :
		rm *.o